benchmark_id: credit_scoring-training_config-germain_credit_risk_v1.0.0
timestamp: '2026-02-01T03:11:35.177152+00:00'
model_architecture:
  model_type: CreditScoringModel
  input_features: 26
  hidden_layers:
  - 256
  - 128
  - 64
  - 64
  use_batch_norm: true
  activation_fn: ReLU
  dropout_rate: 0.1
  output_layer_neurons: 1
  total_parameters: 53313
training_configuration:
  optimizer: Adam
  learning_rate: 0.001
  weight_decay: 0.0001
  loss_function: BCEWithLogitsLoss
  use_pos_weight: false
  epochs_run: 14
  batch_size: 32
final_validation_metrics:
  accuracy: 0.73
  precision: 0.7756
  recall: 0.8643
  f1: 0.8176
  roc_auc: 0.7492
