benchmark_id: credit_scoring-training_config-germain_credit_risk_v1.0.0
timestamp: '2026-02-01T02:44:14.814024+00:00'
model_architecture:
  model_type: CreditScoringModel
  input_features: 26
  hidden_layers:
  - 128
  - 64
  use_batch_norm: true
  activation_fn: ReLU
  dropout_rate: 0.2
  output_layer_neurons: 1
  total_parameters: 12161
training_configuration:
  optimizer: Adam
  learning_rate: 0.001
  weight_decay: 0.0001
  loss_function: BCEWithLogitsLoss
  use_pos_weight: true
  epochs_run: 15
  batch_size: 32
final_validation_metrics:
  accuracy: 0.66
  precision: 0.8396
  recall: 0.6357
  f1: 0.7236
  roc_auc: 0.7568
